kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-hello-work
  namespace: giovanni-manzone-dev
  annotations:
    deployment.kubernetes.io/revision: '3'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sample-hello-work:latest","namespace":"giovanni-manzone-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"container\")].image","paused":false}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-hello-work
  template:
    metadata:
      labels:
        app: sample-hello-work
    spec:
      containers:
        - name: container
          image: 'image-registry.openshift-image-registry.svc:5000/giovanni-manzone-dev/sample-hello-work@sha256:de4ff80d0929d80664a0700124362ec6f7e3c9bbbcfd9dfca7cd1969de425df8'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

